fixtures:
  symlinks:
    syncope: '#{source_dir}'
  forge_modules:
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.5.0"
    stdlib: "puppetlabs/stdlib"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
    concat: "puppetlabs/concat"
    inifile: "puppetlabs/inifile"
    packagecloud:
      repo: "computology/packagecloud"
      ref: "0.3.0"
