source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'metadata-json-lint'
gem 'puppet', '3.8.6'
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'puppet-lint', '>= 1.0.0'
gem 'facter', '>= 1.7.0'
gem 'rspec-puppet'
gem 'beaker'
gem 'beaker-rspec'
gem 'beaker-puppet_install_helper'
gem 'rspec-retry'
