HOSTS:
  syncope-centos-7:
    platform: "el-7-x86_64"
    box: "centos/7"
    box_url: 'https://atlas.hashicorp.com/centos/boxes/7/versions/1603.01/providers/virtualbox.box'
    hypervisor: vagrant
    roles:
      - syncope
CONFIG:
  type: foss
  log_level: verbose
  masterless: true
